services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - ENVIRONMENT=local
    volumes:
      - .:/code
    ports:
      - '8000:8000'
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload --timeout-graceful-shutdown=1
