services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - ENVIRONMENT=production
    networks:
      - proxy
      - default
    expose: [ 8000 ]
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    restart: unless-stopped

networks:
  proxy:
    external: true
